### ISSUE TITLE
Can you add ChatControl Support?

### ISSUE THREAD

**Issue by TomLewis** [Klyser8/Karma#3]
ChatControl Pro has its own regex system for filtering and blocking chat, part of this is being able to set what is triggered for swearing or toxic chat, then you can do as you please, trigger it to be saved to a log etc, For example I have a few words that when used in chat are saved to their own log for racist comments, this lets me know exactly how toxic a few players are.
This would be absolutely fantastic integration as ChatControl has its own Spam system, Swearing system, Toxicity in chat etc but it has no overall "Karma" of a person for doing these things.

**Comment by Klyser8** [comment]
I am not sure I understand what you want me to add to the Karma plugin exactly.

**Comment by TomLewis** [comment]
I think I can do it without integration by just running a karma command when people get flagged.
Leave this for now until can test it.
